export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const USER_CONNECTION = "USER_CONNECTION";
export const CHAT_LIST = "CHAT_LIST";
export const GET_CHAT_LIST = "GET_CHAT_LIST";
export const SET_CURRENT_GAMELIST = "SET_CURRENT_GAMELIST";
